version: '3.8'

services:
  db-1:
    container_name: db-1
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'coffeeapp'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ayaadmin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ayaadmin'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3309'
      # Where our data will be persisted
    volumes:
      - ./db-1:/var/lib/mysql

volumes:
  db-1: